name: Docker CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
      
    - name: Docker Build
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_IMAGE: ${{secrets.DOCKER_IMAGE}}
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_IMAGE:latest
      
    - name: Docker Push
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_IMAGE: ${{secrets.DOCKER_IMAGE}}
      run: docker push $DOCKER_USER/$DOCKER_IMAGE
