name: Docker CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env: 
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username $DOCKERHUB_USERNAME --password-stdin
      
    - name: Docker Build
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_IMAGE: ${{secrets.DOCKERHUB_IMAGENAME}}
      run: |
        docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGENAME
      
    - name: Docker Push
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_IMAGE: ${{secrets.DOCKERHUB_IMAGENAME}}
      run: |
        docker push $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGENAME
